import Head from 'next/head';
export default function Home() {
  return (
    <>
      <Head>
        <title>Some Path Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>some path page</h1>
      </main>
    </>
  );
}
