import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>YOLO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>YOLO!!</h1>
        <p>Content is the same, just demonstrating a localized sub page</p>
      </main>
    </>
  );
}
